name = "TensorsLiteGeometry"
uuid = "f9cc0174-84f8-4243-a119-6cf6c33db921"
version = "0.1.0"
authors = ["Felipe A. V. de Bragança Alves <favbalves@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SmallCollections = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
TensorsLite = "1a1b94bd-d244-45e0-965a-8acfeb92b70f"

[sources]
TensorsLite = {rev = "main", url = "https://github.com/favba/TensorsLite.jl"}

[compat]
LinearAlgebra = "1"
SmallCollections = "0.4.1, 0.5, 0.6"
julia = "1.10"
TensorsLite = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
