name = "TensorsLiteGeometry"
uuid = "f9cc0174-84f8-4243-a119-6cf6c33db921"
authors = ["Felipe A. V. de Bragança Alves <favbalves@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SmallCollections = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
TensorsLite = "1a1b94bd-d244-45e0-965a-8acfeb92b70f"

[compat]
SmallCollections = "0.4.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
